fix offsets, error codes, logging, all output to single dir

diff --git a/scripts/fvs b/scripts/fvs
--- a/scripts/fvs
+++ b/scripts/fvs
@@ -40,14 +40,13 @@ else
     exit 1
 fi
 
-# process the *_original.key files and create offsets 10 offsets at 5 yr intervals
+# process the *_original.key files and create offsets 4 offsets at 5 yr intervals
 echo "Creating offset keyfiles in temp directory"
-python /usr/local/apps/growth-yield-batch/scripts/preproc/CreateOffsets.py $TEMPDIR $TEMPDIR 10 5 | tee offsets.log
+python /usr/local/apps/growth-yield-batch/scripts/preproc/CreateOffsets.py $TEMPDIR $TEMPDIR 4 5 
 if [ $? -ne 0 ]; then
     throw "CreateOffsets.py failed. Check $TEMPDIR/offsets.log" 
     exit 1
 fi
-mkdir -p alt_treelists
 
 # Run all the keyfiles
 for f in *.key
@@ -60,25 +59,29 @@ do
 		echo "Growing $PREFIX..."
 		touch $PREFIX.input.rsp
 		echo $PREFIX.key >  $PREFIX.input.rsp
-		echo alt_treelists/$PREFIX.tre >> $PREFIX.input.rsp
-		echo alt_treelists/$PREFIX.out >> $PREFIX.input.rsp
-		echo alt_treelists/$PREFIX.trl >> $PREFIX.input.rsp
-		echo alt_treelists/$PREFIX.sum >> $PREFIX.input.rsp
-		echo alt_treelists/$PREFIX.chp >> $PREFIX.input.rsp
+        echo $PREFIX.tre >> $PREFIX.input.rsp
+        echo $PREFIX.out >> $PREFIX.input.rsp
+        echo $PREFIX.trl >> $PREFIX.input.rsp
+        echo $PREFIX.sum >> $PREFIX.input.rsp
+        echo $PREFIX.chp >> $PREFIX.input.rsp
 
-		cat $PREFIX.input.rsp | /usr/bin/wine $EXE "$@" 2> $PREFIX.error.log | tee $PREFIX.fvs.log
+		cat $PREFIX.input.rsp | /usr/bin/wine $EXE "$@" | tee $PREFIX.fvs.log
         if [ $? -ne 0 ]; then
             throw "FVS failed" >> $PREFIX.error.log
             cat $PREFIX.error.log
             exit 1
 		fi
-        if [ ! -f alt_treelists/$PREFIX.out ] || [ ! -f alt_treelists/$PREFIX.trl ]; then
+        if [ -f $PREFIX.err ]; then
+            throw "\n !!!!!!!!!!! \n FVS found a $PREFIX.err file" >> $PREFIX.error.log
+            # just warn, don't exit
+            # exit 1
+        fi
+        if [ ! -f $PREFIX.out ] || [ ! -f $PREFIX.trl ]; then
             throw "FVS failed to produce necessary output files" >> $PREFIX.error.log
-            cat $PREFIX.error.log
             exit 1
         fi
 	fi
 done
 
 echo
-echo "Results in temp directory $(pwd)/alt_treelists/"
+echo "Results in temp directory $(pwd)/"
